### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by lurch** [balena-io-modules/drivelist#244]
The README.md still implies that all platforms simply run a script, e.g. it still refers to VBScript.
On Windows this is no longer the case, it now uses a native C++ node module.

**Comment by lurch** [comment]
...and the OSX and Linux parts have now been refactored too, so there's no longer any "external scripts".

**Comment by grumpyoldman-io** [comment]
I also want to add that the contributing section is a bit lacking. The Versionist rules are not transparent.

**Comment by lurch** [comment]
Fixed in https://github.com/balena-io-modules/drivelist/pull/317/commits/3f050852c2847957b2003f79cd73694d162c44fc
