### ISSUE TITLE
Uncaught Error: error: 1114

### ISSUE THREAD

**Issue by hasezoey** [balena-io-modules/drivelist#275]
System: Windows 10 x64 (latest)
node: 10.0.0
drivelist: 6.1.7

```
Uncaught Error: error: 1114\\?\(some path to drivelist.node) at R:\Visual Studio\Projects\project\node_modules\bindings\bindings.js:88 
```

in CLI it works, but in nwjs (+ console from it) it does this error

**Comment by lurch** [comment]
Is this a duplicate of #226 ?

**Comment by hasezoey** [comment]
i dont think so, fixed with using 
```js
exec('wmic LOGICALDISK LIST BRIEF', (err, stdout, stderr) => {
        if (err) {
            console.log(err);
            return;
        }

        var a = stdout.split(' ').filter((v) => {
            v = v.trim();
            if (v && v != "") {
                return v;
            } else return false;
        }).filter((v) => v.includes('\n')).map((v) => v.replace(/\r?\n|\r/g, ''));
        console.log(a);
    });
```

**Comment by lurch** [comment]
This module _used_ to use WMI, but it caused a number of problems so it was switched to using native-code.
See #243 (amongst others) if you're curious.

**Comment by hasezoey** [comment]
i didnt got this module to work and only needed drive letters ... and got this above to work ... when this module should function for nwjs again, i would use it ^^
and with wmi until now i see no problems (and i dont know much about C/C++) 

btw: in Visual Studio is this module not recognized / described

**Comment by hasezoey** [comment]
closing this because i didnt use this project in a long time, and it seems that the issue is not up-to-date anymore
