### ISSUE TITLE
Prebuilds failing on windows

### ISSUE THREAD

**Issue by lefuturiste** [balena-io-modules/drivelist#340]
Hi! I got a problem, I can't build the latest version of drivelist on Windows.

Environment:

- Windows 10 x64 (Surface Pro 3)
- VS Enterprise 2015 with all components
- python 2.7
- npm v6.4.1
- node v10.15.0

Cmd output:
https://gist.githubusercontent.com/StoneSet/483686745455480bbf7a29e9900cf506/raw/9570681645bc8b789a01043a1be788c0cac3e62d/errors%2520install

Detailled log:
https://gist.githubusercontent.com/StoneSet/2e3becb3135531eb84c0534eb0faeef4/raw/e61aa8eebc05a4f65f51642aea44bc38494fc76a/qdsqsd.txt

**Comment by StoneSet** [comment]
Hello,
I'm working on the same project, we managed to build drivelist.

Now we have this error:
https://gist.github.com/StoneSet/50e08c9041ff0c65cf0a3358972f63cb

Regards
Environment: (same)

    Windows 10 x64 (Surface Pro 3)
    VS Enterprise 2015 with all components
    python 2.7
    npm v6.4.1
    node v10.15.0

**Comment by StoneSet** [comment]
FIX : https://github.com/electron/electron/blob/v0.37.2/docs/tutorial/using-native-node-modules.md#using-native-node-modules

Regards

**Comment by lefuturiste** [comment]
> FIX : https://github.com/electron/electron/blob/v0.37.2/docs/tutorial/using-native-node-modules.md#using-native-node-modules
> 
> Regards

We just rebuild the module with the electron context and it's a success. Contact us if you have the same issue and we will be happy to answer.

**Comment by lurch** [comment]
> We just rebuild the module with the electron context and it's a success.

Ahh, so similar to #269 then :wink:
