### ISSUE TITLE
Failed to locate 'CL.exe' when building electron app using drivelist

### ISSUE THREAD

**Issue by hamiltonjoe** [balena-io-modules/drivelist#356]
Running from VSCode does not show this error, only when trying to build and run the electron app. 
I have included the terminal output and the log that it references.

[terminalOutput.txt](https://github.com/balena-io-modules/drivelist/files/3887386/terminalOutput.txt)
[2019-11-25T15_39_18_608Z-debug.log](https://github.com/balena-io-modules/drivelist/files/3887387/2019-11-25T15_39_18_608Z-debug.log)

**Comment by hamiltonjoe** [comment]
The main issue is this line:
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\myappClient\node_modules\drivelist\build\drivelist.vcxproj]

Where is drivelist looking for this executable?

**Comment by hamiltonjoe** [comment]
The things that helped this was:
1. Reinstall Visual Studio 2015 and choose Custom Install, Select Visual C++ during the installation.

Then run the follow commands in VSCode terminal:
2. npm install -global --vs2015 --production windows-build-tools
3. npm config set msvs_version 2015

Then finally set the environment varible to:
4. SET VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140

**Comment by lurch** [comment]
Maybe https://github.com/balena-io/etcher/blob/master/docs/CONTRIBUTING.md#windows helps?
