### ISSUE TITLE
.list is undefined

### ISSUE THREAD

**Issue by ouahibAbdou** [balena-io-modules/drivelist#360]

**Comment by lurch** [comment]
https://github.com/balena-io-modules/drivelist/blob/master/lib/index.ts#L69

I suspect you'll need to provide more info about your problem if you want some help from the drivelist developers?

**Comment by ohager** [comment]
@ouahibAbdou I ran into this issue, using Typescript. 

The following example works for me:
```
import {list} from 'drivelist'

export async function getDrives(): Promise<any[]> { //< type depends on what you want to return
    const drives = await list();
    //... whatever you want to do then    
}

```


PS: Actually, you should provide more info. Example of code, etc.
