### ISSUE TITLE
 Loading non-context-aware native module in renderer

### ISSUE THREAD

**Issue by xiaoxiangmoe** [balena-io-modules/drivelist#373]
(node:82420) Electron: Loading non-context-aware native module in renderer: '/Users/foo/repos/app/node_modules/drivelist/build/Release/drivelist.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

**Comment by warpdesign** [comment]
This happens because the drivelist hasn't been made non-context-aware.

Changing `NODE_MODULE(DriveList, tInitAll)` to `NAN_MODULE_WORKER_ENABLED(DriveList, tInitAll)` in `drivelist.cpp` should fix the problem.

**Comment by zvin** [comment]
fixed in #378
