### ISSUE TITLE
npm update --save problem?

### ISSUE THREAD

**Issue by davuttemel** [balena-io-modules/drivelist#446]
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'drivelist@11.1.0',
npm WARN EBADENGINE   required: { node: '>=16 < 19' },
npm WARN EBADENGINE   current: { node: 'v20.10.0', npm: '10.2.5' }
npm WARN EBADENGINE }

npm update --save give me error. please help me..

**Comment by davuttemel** [comment]
i downgrade node v18 but now electron-builder give me error. 
• install prebuilt binary  name=drivelist version=11.1.0 platform=linux arch=arm64 napi=
  ⨯ cannot build native dependency  reason=prebuild-install failed with error and build from sources not possible because platform or arch not compatible
                                    cause=exit status 1
                                    errorOut=prebuild-install info begin Prebuild-install version 7.1.1

**Comment by otaviojacobi** [comment]
Hello, this should be fixed on latest after #439
